# Generated by Django 4.2 on 2024-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
