# Generated by Django 4.2 on 2024-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Успешно", "Successful"),
                    ("Не успешно", "Unsuccessful"),
                    ("В обработке", "In Process"),
                ],
                default="В обработке",
                max_length=12,
            ),
        ),
    ]
