# Generated by Django 4.2 on 2024-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Последнее обновление"
            ),
        ),
    ]
