# Generated by Django 4.2 on 2024-11-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_owner_alter_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.CharField(max_length=200, verbose_name="ссылка на урок"),
        ),
    ]
