# Generated by Django 4.2 on 2024-11-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_subscription_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("активна", "Active"), ("не активна", "Not Active")],
                default="активна",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
