# Generated by Django 4.2 on 2024-11-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_alter_subscription_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="preview",
        ),
    ]
