# Generated by Django 4.2 on 2024-11-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_remove_lesson_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lessons/", verbose_name="превью"
            ),
        ),
    ]
